Backend/AspNet/toDoWeb/Models/EnumStatusTarefa.cs
namespace toDoWeb.Models
{
    public enum EnumStatusTarefa
    {
        Pendente,
        Finalizado
    }
}

Backend/AspNet/toDoWeb/Models/ErrorViewModel.cs
namespace toDoWeb.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Backend/AspNet/toDoWeb/Models/Tarefa.cs
namespace toDoWeb.Models
{
    public class Tarefa
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public DateTime Data { get; set; }
        public  EnumStatusTarefa Status { get; set; }
    }
}

Backend/AspNet/toDoWeb/Controllers/TarefaController.cs
using Microsoft.AspNetCore.Mvc;
using toDoWeb.Context;
using toDoWeb.Models;

namespace toDoWeb.Controllers;
    public class TarefaController : Controller
    {
    private readonly TarefaContext _context;

    public TarefaController(TarefaContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        var tarefas = _context.Tarefas.ToList();
        return View(tarefas);
    }

     public IActionResult Criar()
        {
            return View();
        }

    [HttpPost]
    public IActionResult Criar(Tarefa tarefa)
    {
        if (ModelState.IsValid)
        {
            _context.Tarefas.Add(tarefa);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        return View(tarefa);
    }

    public IActionResult Editar(int id)
    {
        var tarefa = _context.Tarefas.Find(id);

        if (tarefa == null)
            return RedirectToAction(nameof(Index));

        return View(tarefa);
    }

    [HttpPost]
    public IActionResult Editar(Tarefa tarefa)
    {
        var tarefaBanco = _context.Tarefas.Find(tarefa.Id);

        tarefaBanco.Titulo = tarefa.Titulo;
        tarefaBanco.Descricao = tarefa.Descricao;
        tarefaBanco.Data = tarefa.Data;
        tarefaBanco.Status = tarefa.Status;

        _context.Tarefas.Update(tarefaBanco);
        _context.SaveChanges();

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Detalhes(int id)
    {
        var tarefa = _context.Tarefas.Find(id);

        if (tarefa == null)
            return RedirectToAction(nameof(Index));

        return View(tarefa);
    }

    public IActionResult Deletar(int id)
    {
        var tarefa = _context.Tarefas.Find(id);

        if (tarefa == null)
            return RedirectToAction(nameof(Index));

        return View(tarefa);
    }

    [HttpPost]
    public IActionResult Deletar(Tarefa tarefa)
        {
            var tarefaBanco = _context.Tarefas.Find(tarefa.Id);
            _context.Tarefas.Remove(tarefaBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
}

Backend/AspNet/toDoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lista de Tarefas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/toDoWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lista de Tarefas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Index">Tarefa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - toDoWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Backend/AspNet/toDoWeb/Views/Tarefa/Criar.cshtml
@model toDoWeb.Models.Tarefa

@{
    ViewData["Title"] = "Criar nova tarefa";
}

<h1>Nova tarefa</h1>

<hr>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div class="form-group">
                <label asp-for="Titulo" class="control-lable"></label>
                <input asp-for="Titulo" class="form-control">
            </div>
            <div class="form-group mt-3">
                <label asp-for="Descricao" class="control-lable"></label>
                <input asp-for="Descricao" class="form-control">
            </div>
             <div class="form-group mt-3">
                <label asp-for="Data" class="control-lable"></label>
                <input asp-for="Data" class="form-control">
            </div>
            <div class="form-group mt-3">
                <label asp-for="Status" class="control-lable"></label>
                <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<EnumStatusTarefa>()">
                    <option value="">Defina um status</option>
                </select>
            </div>
            <br>
            <div class="form-group mt-3">
                <input type="submit" value="Criar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary"> Voltar</a>
            </div>
        </form>
    </div>
</div>

Backend/AspNet/toDoWeb/Views/Tarefa/Deletar.cshtml
@model toDoWeb.Models.Tarefa

@{
    ViewData["Title"] = "Deletar contato";
}
<div class="alert alert-danger" role="alert">
    <h1>Deseja realmente deletar a tarefa @Html.DisplayFor(x => x.Id)? Essa operação é irreversível.</h1>
</div>
<hr>
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Titulo)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Titulo)
        </dt>  
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Descricao)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Descricao)
        </dt>  
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Data)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Data)
        </dt>  
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Status)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Status)
        </dt>   
    </dl>
</div>
<form asp-action="Deletar">
    <input type="submit" value="Deletar" class="btn btn-danger">
</form>
<div class="form-group mt-3">
    <a asp-action="Index" class="btn btn-secondary"> Voltar</a>
</div>

Backend/AspNet/toDoWeb/Views/Tarefa/Detalhes.cshtml
@model toDoWeb.Models.Tarefa

@{
    ViewData["Title"] = "Detalhes do contato";
}

<h1>Detalhes da tarefa @Html.DisplayFor(x => x.Id)</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Titulo)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Titulo)
        </dt>  
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Descricao)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Descricao)
        </dt>  
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Data)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Data)
        </dt>  
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Status)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Status)
        </dt>   
    </dl>
</div>
<div class="form-group mt-3">
    <a asp-action="Editar" asp-route-id="@Model.Id" class="btn btn-primary">Editar</a>
    <a asp-action="Deletar" asp-route-id="@Model.Id">
        <button type="button" class="btn btn-danger">Excluir</button>
    </a>
    <a asp-action="Index" class="btn btn-secondary"> Voltar</a>
</div>

Backend/AspNet/toDoWeb/Views/Tarefa/Editar.cshtml
@model toDoWeb.Models.Tarefa

@{
    ViewData["Title"] = "Editar tarefa";
}

<h1>Editar tarefa</h1>

<hr>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div class="form-group">
                <label asp-for="Titulo" class="control-lable"></label>
                <input asp-for="Titulo" class="form-control">
            </div>
            <div class="form-group mt-3">
                <label asp-for="Descricao" class="control-lable"></label>
                <input asp-for="Descricao" class="form-control">
            </div>
            <div class="form-group mt-3">
                <label asp-for="Data" class="control-lable"></label>
                <input asp-for="Data" class="form-control">
            </div>
            <div class="form-group mt-3">
                <label asp-for="Status" class="control-lable"></label>
                <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<EnumStatusTarefa>()">
                    <option value="">Defina um status</option>
                </select>
            </div>
            <br>
            <div class="form-group mt-3">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary"> Voltar</a>
            </div>
        </form>
    </div>
</div>

Backend/AspNet/toDoWeb/Views/Tarefa/Index.cshtml
@model IEnumerable<toDoWeb.Models.Tarefa>

@{
    ViewData["Title"] = "Lista de tarefas";
}

<div class="text-center">
    <h1 class="display-4">Lista de Tarefas</h1>
</div>

<p><a asp-action="Criar" class="btn btn-primary">Nova Tarefa</a></p>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Id)</th>
                <th>@Html.DisplayNameFor(model => model.Titulo)</th>
                <th>@Html.DisplayNameFor(model => model.Descricao)</th>
                <th>@Html.DisplayNameFor(model => model.Data)</th>
                <th>@Html.DisplayNameFor(model => model.Status)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                        <td>@Html.DisplayFor(model => item.Id)</td>
                        <td>@Html.DisplayFor(model => item.Titulo)</td>
                        <td>@Html.DisplayFor(model => item.Descricao)</td>
                        <td>@Html.DisplayFor(model => item.Data)</td>
                        <td>@Html.DisplayFor(model => item.Status)</td>
                        <td>
                            <a asp-action="Editar" asp-route-id="@item.Id">
                                <button type="button" class="btn btn-outline-primary">Editar</button>
                            </a>
                            <a asp-action="Detalhes" asp-route-id="@item.Id">
                                <button type="button" class="btn btn-outline-secondary">Detalhes</button>
                            </a>
                            <a asp-action="Deletar" asp-route-id="@item.Id">
                                <button type="button" class="btn btn-outline-danger">Excluir</button>
                            </a>
                        </td>
                    </tr>
            }
        </tbody>
    </table>
</div>